#+TITLE: P3 Notes
* Requirements
- include/lock.h contains all lock variants
- each lock variant has seperate .c file
- no reliance on semaphores or interrupts
- assume a fixed number of locks
- no need to implement lock delete function
- return syserr if max number of locks of a particular type is reached
- unlock system calls return syserr if process tries to release a lock that it doesnt own
* Spinlock
- needs initialization
- needs lock function
- needs unlock function
- sl_lock_t can be defined how I wish
- spinlock implementation should be in system/spinlock.c
- include in lock.h constant NSPINLOCKS definingh the max number of spinlocks that can be used, set NSPINLOCKS = 20
** syscalls
- syscall sl_initlock(sl_lock_t *lock)
- syscall sl_lock(sl_lock_t *lock)
- syscall sl_unlock(sl_lock_t *lock)
** test case
- creates a process called nthreads, nthreads creates nthreads number of processes called increment
- create nthreads
  #+BEGIN_SRC c
create((void *)nthreads, INITSTK, 1,"nthreads", 4, nt, &x, value/nt, &mutex)
  #+END_SRC
  + args
    - funcaddr -> nthreads
    - INITSTK -> stack size
    - priority -> 1
    - name -> "nthreads"
    - nargs -> 4
      + nt -> number of threads
      + n -> value/nt
      + &x -> address of shared variable being incremented
- create increment
  #+BEGIN_SRC c
create((void *)increment, INITSTK, 1,"p", 3, x, n, mutex)
  #+END_SRC
  - args
    - x -> shared variable
    - n -> value/nt
    - mutex -> lock
** errors
- with 50 threads, the process gets stuck trying to receive a message after the 48th thread finished
- Where the problem *isn't*
  - resched_cntl
** simple lock test
#+BEGIN_SRC c
/* basic mutex testing  */
old_val = mutex.lock_value;
owner = mutex.lock_owner;
sync_printf("\nSpinlock created, lock value = %d, lock owner = %X\n", old_val, owner);
sl_lock(&mutex);
owner = mutex.lock_owner;
old_val = mutex.lock_value;
sync_printf("\nSpinlock locked, lock value = %d, lock owner = %X\n", old_val, owner);
end of basic mutex testing

returnVal = test_and_set(pointer_to_old_val, new_val);
sync_printf("Return value: %x\n", returnVal);
#+END_SRC
* lock
- add the following
  - syscall initlock(lock_t *t)
  - syscall lock(lock_t *t)
  - syscall unlocklock(lock_t *t)
- implement
  - park
  - unpark
  - setpark
  - http://pages.cs.wisc.edu/~remzi/OSTEP/threads-locks.pdf
* al_lock
- Automatically detect the presence of deadlocks due to circular deps
  (dead locks involving multiple locks)
- Notify presence of deadlock as soon as deadlock is originiated
- Locks originate when a cyclic dep is created, lock detection code should be part of init
- Lock detection should be part of al_lock system call
** Deadlock
lock 1 -> waiting on -> lock 2
lock 2 -> waiting on -> lock 3
lock 3 -> waiting on -> lock 1

* Stack Information
#+BEGIN_SRC C
int bar(int a, int b){
    int x, y;
    x = 555;
    y = a + b;
    return y;

}

void foo(void){
    bar(111, 222)
}
#+END_SRC
| Bottom of stack (in foo(void))         | Bottom of stack |                                                   |
| Saved EBP                              |                 |                                                   |
| 222                                    |                 |                                                   |
| 111                                    |                 | Now foo calls bar()                               |
| return address to foo                  |                 | On entry into bar, previous value of ebp is saved |
| saved ebp from foo                     | ebp             |                                                   |
| x                                      |                 |                                                   |
| y                                      |                 |                                                   |
| test_and_set(uint32 arg1, uint32 arg2) |                 |                                                   |
* Note on assembly function
  - Consider that, after ptr is read into EBX, EBX contains just a memory address. The xchg instruction needs to read the value at that memory location. So, you will need to use indirection to read and write memory: (EBX)
  - () -> indirection: get value at memory location %x
  - %ebp is a register, (%ebp) is the content of the register, x(%ebp) is an x offset from the content of the register
  - if your code uses EBX, you want to save the value of EBX on the stack after saving the value of EBP.
  - You don't need " movl 4(%ebp), %esp" at the end because the value of ESP is updated automatically.
  - At the end you need to pop EBX and EBP from the stack because you had pushed them on the stack at the beginning. But, you should not call popal, because it would pop all registers from the stack. But, you had not used pushal before, and so the content expected by popal is not on the stack.
* Test and set
#+BEGIN_SRC C
uint32 test_and_set(uint32 *ptr, uint32 new_value) {
    uint32 old_value = *ptr;
    *ptr = new_value;
    return old_value;
}
#+END_SRC
#+BEGIN_SRC asm
// working version, doesn't use xchg
test_and_set:
    pushl	%ebp
    movl	%esp, %ebp
    pushl %edx
    movl	8(%ebp), %eax // ptr to old_value
    movl	(%eax), %eax // return old_value, old_value = *ptr -> save content of old value to return register
    movl	%eax, -4(%ebp) // write %eax to return register???
    movl	8(%ebp), %eax // get ptr to old value again
    movl	12(%ebp), %edx // get new value
    movl	%edx, (%eax) // store new value at address indicated by old_value
    movl	-4(%ebp), %eax // load old_value into return value
    pop %edx
    pop %ebp
    ret

// working version, uses xchg, not atomic enough
test_and_set:
    pushl	%ebp
    movl	%esp, %ebp
    pushl %edx

    movl	8(%ebp), %eax // ptr to old_value
    movl	(%eax), %eax // return old_value, old_value = *ptr -> save content of old value to return register
    movl	%eax, -4(%ebp) // store value of *ptr in this functions frame
    movl	8(%ebp), %eax // get ptr to old value again
    movl	12(%ebp), %edx // get new value
    xchg    %edx, (%eax) // store new value at address indicated by old_value
    movl	-4(%ebp), %eax // load old_value (in this functions frame) into return register

    pop %edx
    pop %ebp
    ret

#+END_SRC
* Simple assembly addition function for reference
#+BEGIN_SRC asm
add_func:
    // eax used as return register
    pushl %ebp // store current ebp value onto stack
    //() -> indirection: get value at memory location %x
    movl %esp, %ebp // save current stack pointer into ebp register
    //%ebp is a register, (%ebp) is the content of the register, x(%ebp) is an x offset from the content of the register
    movl 8(%ebp), %edx // get arg 1 that was passed, store into ecx
    movl (%edx), %edx
    movl 12(%ebp), %eax // get arg 2 that was passed, store into eax

    addl %edx, %eax // add contents of eax and ebx, store into ebx
    popl %ebp
    ret
#+END_SRC
* Deadlock
** Creating a dealock
#+BEGIN_SRC c
foo(lock *l_a, lock *l_b, lock *l_c){
    lock(l_a);
    /*critical a*/
    lock(l_b);
    /*critical b*/
    unlock(l_a); // lock a is available
    /*critical c*/
    lock(l_c);
    unlock(l_b); // lock b is available
    lock(l_a);
    unlock(lock_c);
    unlock(lock_a);
    /*other*/
    lock(l_b);
    /*critical_b*/
    unlock(l_b);
    /*other*/
    lock(l_c);
    /*critical_c*/
    lock(l_a);
    /*critical_d*/
    unlock(l_a);
    /*other*/
    unlock(l_c);
    /*other*/
}
#+END_SRC
| Processes                                     |   |
| Process 1 gets lock la, starts executing code |   |
| Other processes wait                          |   |
| Process 1 releases lock la, get lock lb       |   |
| Process 2 gets lock la                        |   |
| Other processes wait                          |   |
| Process 1 releases lock                       |   |
|                                               |   |

t = 0
 | Locks | Owner     |
 | l_a   | Process 1 |
 | l_b   | -         |
 | l_c   | -         |
t = 1
 | Locks | Owner      |
 | l_a   | Process 2  |
 | l_b   | Process 1  |
 | l_c   | -          |
t = 2
 | Locks | Owner     |
 | l_a   | Process 3 |
 | l_b   | Process 2 |
 | l_c   | Process 1 |

 Now process 1 is attempting to get lock a, but lock a is held by process 3
 Process 2 is attempting to get lock c, 
